### ISSUE TITLE
Add Keyboard Support to Calculator

### ISSUE THREAD

**Issue by yingmo55** [yingmo55/Calculator#7]
**Is your feature request related to a problem? Please describe.**  
Currently, the calculator only supports touch/mouse inputs and limited keyboard input via using <kbd>tab</kbd> and <kbd>tab</kbd> + <kbd>shift</kbd>. Adding keyboard support will make it and more convenient to use. 

**Describe the solution you'd like**  
Add an event listener to listen to the [keydown event](https://developer.mozilla.org/en-US/docs/Web/API/Document/keydown_event)
and check if the input value matches one of the button for the calculator.

**For Contributors / Suggestions**  
If you would like to help with this task or have a better solution, please leave a comment here. I'll assign the task to you if you would like to contribute!

**Comment by RubenLeerentveld** [comment]
Submitted an pull request! ❤️

**Comment by yingmo55** [comment]
Thank you again for taking an interest in this project! I appreciate the work and feedback you gave. The issue is now closed.
