### ISSUE TITLE
Add Display of Current Operation Key in the Display Section

### ISSUE THREAD

**Issue by yingmo55** [yingmo55/Calculator#8]
**Is your feature request related to a problem? Please describe.**
Currently, there is no visual indication on what operation the calculator is performing. I would like to add it to the display for better user experience.
My previous attempt (see [this commit](https://github.com/yingmo55/Calculator/pull/5/commits/bb5a518da107d6367428fef581f198144045dd23) for more details) at implementing this feature did not work as expected; The symbol display did not update properly after using the <kbd>=</kbd> equal function.

**Describe the solution you'd like**
When the user clicks one of the operator keys (plus, minus, multiply, divide), the corresponding symbol should show up on the left side of the display. It should disappear when a user clicks on the "equal" key, and reappear after using one of the operators.

**For Contributors / Suggestions**
If you would like to help with this task or have a better solution, please leave a comment here. I'll assign the task to you if you would like to contribute!

**Comment by Olaleye-Blessing** [comment]
Can I work on this?
